name = "sketch_css"
version = "1.0.0"

description = "A Sketch runtime package, made to generate CSS!"
internal_modules = ["sketch/internals", "sketch/internals/*"]
licences = ["MIT"]
links = [{title = "Sponsor", href = "https://github.com/sponsors/ghivert"}]
repository = {type = "github", user = "ghivert", repo = "sketch"}

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glance = ">= 0.11.0 and < 1.0.0"
sketch = { path = "../sketch" }
simplifile = ">= 2.0.1 and < 3.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
glint = ">= 1.0.1 and < 2.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
